gpg_key_path: '.secure_files/autoupdate.asc'

providers:
  - type: 'github'
    token: '.secure_files/github_access_token.key'
    organizations:
      - 'rios0rios0'

updaters:
  terraform:
    enabled: true
    auto_complete: false
    target_branch: 'main'
  golang:
    enabled: true
    target_branch: 'main'
